version: "3"
services:
  datascience-notebook:
    image: jupyter/scipy-notebook
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 7777:8888
    container_name: datascience-notebook-container
